# Generated by Django 5.2.1 on 2025-06-15 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_message_unread_alter_message_parent_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='unread',
        ),
    ]
