# Generated by Django 5.2.1 on 2025-06-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_remove_message_unread'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='unread',
            field=models.BooleanField(default=True, verbose_name='Unead'),
        ),
    ]
