# Deployment for our MySQL database using Secret for the password and
# PersistentVolumeClaim for storage
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: django-mysql-configmap 
                  key: DATABASE_NAME
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: django-mysql-configmap 
                  key: DATABASE_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: django-mysql-secrets 
                  key: DATABASE_PASSWORD
            - name: MYSQL_ROOT_PASSWORD # Also required by the MySQL image
              valueFrom:
                secretKeyRef:
                  name: django-mysql-secrets 
                  key: DATABASE_PASSWORD
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-persistent-volume-claim